version: '3'

services:
  db:
    container_name: db
    image: mysql:5.7
    volumes:
      - ./db/volumes:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass1234
      MYSQL_DATABASE: public
  api:
    container_name: api
    build: .
    volumes:
      - ./:/go/src
    ports:
      - 8080:8080
    depends_on:
      - db
