version: '3'

services:
  db:
    container_name: db
    image: mysql:5.7
    volumes:
      - ./db/volumes:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: pass1234
      MYSQL_DATABASE: public
  api:
    container_name: api
    build: .
    volumes:
      - ./:/go/src/github/go-api-by-generator
    ports:
      - 8080:8080
    environment:
      DB_DRIVER: mysql
      DB_HOST: db
      DB_NAME: public
      DB_USER: root
      DB_PASSWORD: pass1234
    command: go run main.go
    restart: always
    tty: true
    depends_on:
      - db
