/*
 * HogeHoge
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// UserResponse - ユーザモデル
type UserResponse struct {

	Id int32 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Age int32 `json:"age,omitempty"`

	Weight int32 `json:"weight,omitempty"`

	CreatedAt string `json:"created_at,omitempty"`

	UpdatedAt string `json:"updated_at,omitempty"`
}
