openapi: 3.0.0
info:
  title: HogeHoge
  version: 1.0.0
servers:
- description: Localhost server
  url: http://localhost:9002
- description: Development server
  url: http://dev.api.example.com
- description: Production server
  url: https://api.example.com
paths:
  /users:
    get:
      parameters:
      - description: 並び順2
        explode: true
        in: query
        name: order_by2
        required: false
        schema:
          type: string
        style: form
      - description: 並び順
        explode: true
        in: query
        name: order_by
        required: false
        schema:
          type: string
        style: form
      - description: 取得件数
        explode: true
        in: query
        name: limit
        required: false
        schema:
          type: integer
        style: form
      - description: ページング用パラメータ
        explode: true
        in: query
        name: page
        required: false
        schema:
          type: integer
        style: form
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/UserResponse'
                type: array
          description: ユーザの一覧を返します
  /users/{userId}:
    post:
      parameters:
      - description: user id
        explode: false
        in: path
        name: userId
        required: true
        schema:
          type: integer
        style: simple
      responses:
        200:
          description: ok
components:
  schemas:
    UserResponse:
      description: ユーザモデル
      example:
        id: 1
        name: koba
        age: 33
        weight: 80
        created_at: 2014-10-10T13:50:40+09:00
        updated_at: 2014-10-10T13:50:40+09:00
      properties:
        id:
          type: integer
        name:
          type: string
        age:
          type: integer
        weight:
          type: integer
        created_at:
          type: string
        updated_at:
          type: string
      type: object
